WORKFLOW_TEMPLATES = [
    {
        "id": "email-triage",
        "name": "Email Triage",
        "emoji": "📧",
        "description": "Auto-sort, prioritize, and respond to emails based on urgency and sender importance",
        "category": "productivity",
        "integrations": ["gmail"],
        "trigger": "email_received",
        "steps": ["classify_urgency", "check_sender_vip", "draft_response", "route_or_reply"],
        "guardrails": ["no-auto-reply-external", "escalate-vip"],
        "popularity": 95,
    },
    {
        "id": "invoice-tracker",
        "name": "Invoice Tracker",
        "emoji": "💰",
        "description": "Extract invoice data from emails and auto-log to spreadsheets",
        "category": "finance",
        "integrations": ["gmail", "sheets"],
        "trigger": "email_received",
        "steps": ["detect_invoice", "extract_amount", "log_to_sheet", "send_confirmation"],
        "guardrails": ["verify-amount"],
        "popularity": 88,
    },
    {
        "id": "standup-bot",
        "name": "Standup Bot",
        "emoji": "🤖",
        "description": "Collect daily standups from Slack and generate summary reports",
        "category": "team",
        "integrations": ["slack", "sheets"],
        "trigger": "schedule_daily",
        "steps": ["collect_updates", "summarize", "post_summary", "log_report"],
        "guardrails": [],
        "popularity": 82,
    },
    {
        "id": "customer-support",
        "name": "Customer Support",
        "emoji": "🎧",
        "description": "Triage support tickets, suggest responses, escalate complex issues",
        "category": "support",
        "integrations": ["gmail", "slack"],
        "trigger": "email_received",
        "steps": ["classify_issue", "check_knowledge_base", "draft_response", "escalate_if_complex"],
        "guardrails": ["human-approval-refund", "no-promise-timeline"],
        "popularity": 91,
    },
    {
        "id": "content-scheduler",
        "name": "Content Scheduler",
        "emoji": "📅",
        "description": "Plan, draft, and schedule social media content across platforms",
        "category": "marketing",
        "integrations": ["sheets", "slack"],
        "trigger": "schedule_weekly",
        "steps": ["analyze_trends", "draft_content", "review_queue", "schedule_posts"],
        "guardrails": ["brand-voice-check"],
        "popularity": 76,
    },
    {
        "id": "data-pipeline",
        "name": "Data Pipeline",
        "emoji": "🔄",
        "description": "Extract, transform, and sync data between services automatically",
        "category": "engineering",
        "integrations": ["sheets", "http"],
        "trigger": "schedule_hourly",
        "steps": ["fetch_source", "transform_data", "validate", "sync_destination"],
        "guardrails": ["rate-limit", "data-validation"],
        "popularity": 70,
    },
    {
        "id": "meeting-assistant",
        "name": "Meeting Assistant",
        "emoji": "🗓️",
        "description": "Prepare agendas, take notes, distribute action items after meetings",
        "category": "productivity",
        "integrations": ["gmail", "slack", "sheets"],
        "trigger": "calendar_event",
        "steps": ["prepare_agenda", "collect_notes", "extract_actions", "distribute"],
        "guardrails": [],
        "popularity": 85,
    },
    {
        "id": "security-monitor",
        "name": "Security Monitor",
        "emoji": "🛡️",
        "description": "Monitor logs and alerts for security anomalies, auto-respond to incidents",
        "category": "security",
        "integrations": ["slack", "http"],
        "trigger": "webhook",
        "steps": ["ingest_alert", "classify_severity", "correlate_events", "notify_or_respond"],
        "guardrails": ["no-auto-block-production", "escalate-critical"],
        "popularity": 73,
    },
]
